

<style>
	* {
            font-family: Verdana, Geneva, Tahoma, sans-serif;
        }
	.footer {
            border: 1px solid grey;
            height: 80px ;
            margin-top: 3px;
            background-color: lightgrey;
            text-align: center;
            vertical-align: middle;

        
        }
}
    
   
        
</style>
<div class="footer">

<a  class="animated infinite heartBeat delay-2s"> <span><b> This is Footer Guy's !</b></a>
</div>