 <?php 
// echo 111; die;
 // echo"<pre>";
 // print_r($this); die();
 
// $products = $this->getProducts();
$url=Ccc::getModel('Core_Url');
        // $this->;
$products = $this->getProducts();
// echo "<pre>";
// print_r($products); die();
// echo "<pre>";
// print_r($this);
// die();







?>





    <div class="content-main">
        <div class="content">
            <h2>Manage Product Content</h2>
            <a href="<?php echo ($url->getUrl('product','add'));?>">Add Product</a>
        
        </div>
        <div>
            <table border="3px" width="80%">
                <tr>
                    <th>Product_id</th>
                    <th>Name</th>
                    <th>SKU</th>
                    <th>Cost</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>Status</th>
                    <th>Color</th>
                    <th>Material</th>
                    <th>inserted_at</th>
                    <th>updated_at</th>
                   <!--  <th>Thumbnail</th>
                    <th>Small</th>
                    <th>Base</th> -->
                    <th>Media</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>

                <?php
                //feching data to form from database
                foreach($products->getData() as $row){

                ?>

                <tr>
                    <!-- all attributes of database -->
                    <td><?php echo $row->product_id; ?></td>
                    <td><?php echo $row->name; ?></td>
                    <td><?php echo $row->sku; ?></td>
                    <td><?php echo $row->cost; ?></td>
                    <td><?php echo $row->price; ?></td>
                    <td><?php echo $row->description; ?></td>
                    <td><?php echo $row->getStatusText(); ?></td>
                    <td><?php echo $row->color; ?></td>
                    <td><?php echo $row->material; ?></td>
                    <td><?php echo $row->inserted_at; ?></td>
                    <td><?php echo $row->updated_at; ?></td>
                   
                    
                    <td><a href="Index.php?c=product_media&a=grid&id=<?php echo $row->product_id; ?>">ProductMedia</a></td>
                    <td><a href="<?php echo ($url->getUrl('product','edit',['id'=>$row->product_id]));?>">edit</a></td>
                    <td><a href="<?php echo ($url->getUrl('product','delete',['id'=>$row->product_id]));?>">delete</a></td>
                </tr>
                <?php
                }
                ?>
            </table>

        </div>
    </div>  
 <td><input type="radio" name="thumb" value="<?php echo $row->getThumb();?>"></td>
                    <td><input type="radio" name="small" value="<?php echo $row->image_id; ?>" <?php $row->getSmall();?>></td>
                    <td><?php echo $row->getBase(); ?></td>