<?php

$url = new Model_Core_Url();
$shippings = $this->getShippings();


?>
    <div class="content-main">
        <div class="content">
            <h2>Manage Shipping Content</h2>
            <a href="<?php echo ($url->getUrl('shipping','add'));?>">Add Shipping</a>
        </div>
        <div>
            <table border="1px">
                <tr>
                    <th style="width : 20px">Shipping_method_id</th>
                    <th>Name</th>
                    <th>Amount</th>
                    <th>Status</th>
                    <th>inserted_at</th>
                    <th>updated_at</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                <?php
                //feching data to form from database
                foreach($shippings->getData() as $row){

                ?>

                <tr>
                    <!-- all attributes of database -->
                    <td><?php echo $row->shipping_id; ?></td>
                    <td><?php echo $row->name; ?></td>
                    <td><?php echo $row->amount; ?></td>
                    <td><?php echo $row->getStatusText(); ?></td>
                    <td><?php echo $row->inserted_at; ?></td>
                    <td><?php echo $row->updated_at; ?></td>
                    
                    <td><a href="<?php echo ($url->getUrl('shipping','edit',['id'=>$row->shipping_id]));?>">edit</a></td>
                    <td><a href="<?php echo ($url->getUrl('shipping','delete',['id'=>$row->shipping_id]));?>">delete</a></td>
                </tr>
                <?php
                }
                ?>
            </table>
        </div>
    </div>
      