<?php 
$attribute = $this->getAttribute();
$row = $this->getRow();
$options = $attribute->getOptions();
?>
<select>
    <option value="0">Select</option>
    <?php if($options->count()>0): ?>
        <?php foreach ($options->getData() as $option) :?>
        <?php $selected = ($row->getAttributeValue($attribute) == $option->option_id)? 'selected':'' ?>
        <option value="<?php echo $option->option_id ?>" <?php echo $selected; ?>><?php echo $option->name ?></option>
        <?php endforeach; ?>
    <?php endif; ?>
</select>