<?php

$url = new Model_Core_Url();

$cart=$this->getRow();
$customers = $cart->getCustomers();
$billingAddress = $cart->getBillingAddress();
$shippingAddress = $cart->getShippingAddress();
$customerId = Ccc::getModel('Core_Session')->get('customer_id');




?>


    <div class="content-main">
        <form action="<?php echo ($url->getUrl('save','cart'));?>" method="post">
            <table>
                <tr>
                    <td>
                        <h1> Cart Details</h1>
                    </td>
                    <a href="<?php echo ($url->getUrl('grid','order',null,true));?>">Cancel</a>
                        
                        <button type="submit">Save</button>
                    </td>
                </tr>
            </table>
            <table border="2px" style="border-collapse: collapse">
         
                <tr>
                    <td>Customer </td>
                    <td colspan="3">
                    <select class="col-2" onchange="changeCustomer(this.value)">
                    <option value="0">Select</option>
                    <?php foreach ($customers->getData() as $customer) :?>
                    <?php $selected = ($customer->customer_id == $customerId)?'selected':'';?>
                    <option value="<?php echo $customer->customer_id ?>" <?php echo $selected ?>><?php echo $customer->first_name ?></option>
                    <?php endforeach; ?>
                    </select>
                    </td>
                </tr>  
                <tr>
                    <td class="col-1">Email : </td>
                    <td class="col-2"><?php echo $cart->getCustomer($customerId)->email ?></td>
                    <td class="col-1">Mobile No. : </td>
                    <td class="col-2"><?php echo $cart->getCustomer($customerId)->mobile ?></td>
                </tr>
            </table>
        </form>
    </div>
       