<?php

$url = new Model_Core_Url();
// $brand = $this->brand;
// print_r($brand); die();
$row=$this->getRow();



?>


    <div class="content-main">
        <form action="<?php echo ($url->getUrl('save','brand'));?>" method="post">
            <table>
                <tr>
                    <td>
                        <h1>Save Brand Details</h1>
                    </td>
                    <a href="<?php echo ($url->getUrl('grid'));?>">Cancel</a>
                        
                        <button type="submit">Save</button>
                    </td>
                </tr>
            </table>
            <table border="2px" style="border-collapse: collapse">
         
                <tr>
                    <td>Name: </td>
                    <td><input type="text" name="brand[name]" value="<?php echo $row->name;?>"></td>
                </tr>
                <tr>
                    <td>Description: </td>
                    <td><input type="text" name="brand[description]" value="<?php echo $row->description;?>"></td>
                </tr>
                <tr>
                    <td>Image: </td>
                    <td><input type="text" name="brand[image]" value="<?php echo $row->image;?>"></td>
                </tr>

                
                
            </table>
        </form>
    </div>
       