
<!DOCTYPE html>
<html>
<?php $this->createBlock('Html_Head')->render(); ?>

<body>
	<table border="2px" width="100%" height="100%" cellpadding="2px">
	<tr class="header"><td><?php echo $this->getChildHtml('header') ?></td></tr>
	<tr class="message"><td><?php echo $this->getChildHtml('message') ?></td></tr>
	<tr class="content"><td>				<td><?php echo $this->getChildHtml('content') ?></td>
</td></tr>
	<tr class="footer"><td><?php echo $this->getChildHtml('footer') ?></td></tr>
	</table>

</body>
</html>