
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<style>
		.header{
			height: 100px;
		}
		.message{
			height: 20px;
		}
		.footer{
			height: 100px;
		}
		.content{
			height: 500px;
		}

	</style>
</head>
<body>
	<table border="2px" width="100%" height="100%" cellpadding="2px">
	<tr class="header"><td>Header</td></tr>
	<tr class="message"><td>Message</td></tr>
	<tr class="content"><td>Content</td></tr>
	<tr class="footer"><td>footer</td></tr>
	</table>

</body>
</html>