
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<style>
		.header{
			height: 100px;
			
		}
		.message{
			height: 20px;
		}
		.footer{
			height: 100px;
		}

	</style>
</head>
<body>
	<table border="2px" width="100%">
	<tr class="header"><td colspan="3" width="100%"><?php $this->getChild('header')->render();?></td></tr>
	<tr class="message"><td colspan="3"><?php $this->getChild('message')->render(); ?></td></tr>
	<tr class="content">
		<!-- <td><?php $this->getChild('left')->render(); ?></td> -->
		<td><?php $this->getChild('content')->render();?></td>
		<!-- <td><?php $this->getChild('right')->render(); ?></td>	 -->
	</tr>
	<tr class="footer"><td colspan="3"><?php $this->getChild('footer')->render();?></td></tr>
	


	</table>

</body>
</html>