
<?php echo $this->getChild('head')->toHtml(); ?>
<body>
	<table border="2px" width="100%">
	<tr class="header"><td colspan="3" width="100%"><?php echo $this->getChildHtml('header');?></td></tr>
	<tr class="message"><td colspan="3"><?php $this->getChild('message')->render(); ?></td></tr>
	<tr class="content">
		<!-- <td><?php echo $this->getChildHtml('left');?></td> -->
		<td><?php echo $this->getChildHtml('content');?></td>
		<!-- <td><?php echo $this->getChildHtml('right');?></td>	 -->
	</tr>
	<tr class="footer"><td colspan="3"><?php echo $this->getChildHtml('footer');?></td></tr>
	


	</table>

</body>
</html>