
<!DOCTYPE html>
<html>
<?php $this->createBlock('Html_Head')->render(); ?>
<body>
	<table border="2px" width="100%">
	<tr class="header"><td colspan="3" width="100%"><?php $this->getChild('header')->render();?></td></tr>
	<tr class="message"><td colspan="3"><?php $this->getChild('message')->render(); ?></td></tr>
	<tr class="content">
		<!-- <td><?php $this->getChild('left')->render(); ?></td> -->
		<td><?php $this->getChild('content')->render();?></td>
		<!-- <td><?php $this->getChild('right')->render(); ?></td>	 -->
	</tr>
	<tr class="footer"><td colspan="3"><?php $this->getChild('footer')->render();?></td></tr>
	


	</table>

</body>
</html>