<?php 

$products = $this->getProducts();
$shippings = $this->getShipping();
$carts = $this->getCart();

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<style>
		.content-main{
			margin: 10px;
		}
	</style>
</head>
<body>
	<div class="content-main">
		<table width="60%">
			<tr>
				<form action="Index.php?c=cart&a=insert" method="post">
					<td>
						<select name="cart[item]">
						<option value="0">SELECT PRODUCTS</option>

							<?php foreach ($products as $product) { ?>
								<option value="<?php echo $product['product_id']."=".$product['cost']."=".$product['price'] ?>"><?php echo $product['name']."- $".$product['price']; ?></option>
							<?php } ?>
						</select>
					</td>
					<td>
						<input type="number" name="cart[quantity]">
					</td>
					<td>
						<button type="submit">ADD ITEM</button>
					</td>
				</form>
			</tr>
			<tr>
				<td>
					<select>
						<option value="0">SELECT SHIPPING SERVICES</option>
						<?php foreach ($shippings as $shipping) { ?>
							<option value="<?php echo $shipping['amount'] ?>"><?php echo $shipping['name']."- $".$shipping['amount']; ?></option>
						<?php } ?>
					</select>
				</td>
				<td></td>
				<td>
					<button type="submit">Save</button>
				</td>
			</tr>
			<tr>
				<td>
					<input type="number" name="">
				</td>
				<td></td>
				<td>
					<button type="submit">Save</button>
				</td>
			</tr>
		</table>
		<table width="70%">
			<tr>
				<td width="70%"><h2>CART ITEMS</h2></td>
			<form action="Index.php?c=cart&a=update" method="post">
				<td width="30%"><button type="submit">UPDATE</button></td>
			</tr>
		</table>
		<table border="3px" width="100%">
			<tr>
				<th>PRODUCT ID</th>
				<th>NAME</th>
				<th>SKU</th>
				<th>PRICE</th>
				<th>QUANTITY</th>
				<th>ROW TOTAL</th>
				<th>REMOVE</th>
			</tr>


			<?php foreach ($carts as $cart) { ?>
				<tr>
					<td><?php echo $cart['product_id']; ?></td>
					<td><?php echo $cart['name']; ?></td>
					<td><?php echo $cart['sku']; ?></td>
					<td><?php echo $cart['price']; ?></td>
					<td><input type="number" name="quantity[<?php echo $cart['cart_item_id'] ?>]" value="<?php echo $cart['quantity']; ?>"></td>
					<td><?php echo $cart['quantity']*$cart['price']; ?></td>
					<td><a href="Index.php?c=cart&a=delete&id=<?php echo $cart['cart_item_id']; ?>">Remove</a></td>
				</tr>
			<?php } ?>
			</form>
		</table>
		<table border="3px" width="20%">
			<tr>
				<td>SUB TOTAL:</td>
				<td></td>
			</tr>
			<tr>
				<td>SHIPPING AMOUNT:</td>
				<td><?php echo $shipping['amount'] ?></td>

			</tr>
			<tr>
				<td>TAX(5%):</td>
				<td></td>
			</tr>
			<tr>
				<td>GRAND TOTAL:</td>
				<td></td>
			</tr>
		</table>
	</div>
</body>
</html>