<?php $pager = $this->getPager() ?>

    <div>
    <?php if($pager->getNumberOfPage()>1): ?>
        <div>
            <nav>
                <ul>
                    <li  id="start">
                        <a class=" <?php echo ($pager->getStart() == 0) ? 'disabled':'' ?>" onclick="ajax.setUrl('<?php echo $this->getUrl('grid',Null,['p'=>$pager->getStart()]) ?>').call()">Start</a>
                    </li>
                    <li id="previous">
                        <a class=" <?php echo ($pager->getPrevious() == 0) ? 'disabled':'' ?>" onclick="ajax.setUrl('<?php echo $this->getUrl('grid',Null,['p'=>$pager->getPrevious()]) ?>').call()">Previous</a>
                    </li>
                    <li >
                        <a ><?php echo $pager->getCurrentPage() ?></a>
                    </li>
                    <li  id="next">
                        <a class="  <?php echo ($pager->getNext() == 0) ? 'disabled':'' ?>" onclick="ajax.setUrl('<?php echo $this->getUrl('grid',Null,['p'=>$pager->getNext()]) ?>').call()">Next</a>
                    </li>
                    <li  id="end">
                        <a class=" <?php echo ($pager->getEnd() == 0) ? 'disabled':'' ?>" onclick="ajax.setUrl('<?php echo $this->getUrl('grid',Null,['p'=>$pager->getEnd()]) ?>').call()">End</a>
                    </li>
                </ul>
            </nav>
        </div>
    <?php else: ?>
        <div></div>
    <?php endif; ?>
        <div>
            <span >Page <?php echo $pager->getCurrentPage(); ?></span> of <span class="fst-italic fw-bold">Total <?php echo $pager->getNumberOfPage() ?></span>
        </div>
        <div >
            <select name="recordCount" id="showRecordCount" onchange="rpp(this.value)">
                <?php foreach ($pager->getRecordPerPageOption() as $option) :?>
                    <?php $selected = ($pager->getRecordPerPage() == $option) ? 'selected':'' ?>
                <option value="<?php echo $option ?>" <?php echo $selected ?>><?php echo $option ?></option>
                <?php endforeach; ?>
            </select>
            <input type="hidden" name="p" id="page-no">
        </div>
    </div>

<script type="text/javascript">
    function rpp(value) {
        ajax.setUrl('<?php echo $this->getUrl('grid',Null,['p'=>1]) ?>&rpp='+value).call();
    }
</script>